Backport 2.12 to 0.7.x branch
twitter/chill pull request #274
Opened 2017-01-03 22:50 UTC by johnynek

This brings e5afee8da3681829a0ed0fb8edd9549488f4efaf to the 0.7.x (Kryo 2.21) branch.

2017-01-03 22:51 UTC, johnynek commented
@sritchie @isnotinvain review?

2017-01-04 00:09 UTC, sritchie-stripe requested changes

2017-01-04 00:09 UTC, sritchie-stripe commented on README.md
> +Chill modules are available on Maven Central. The current groupid and version for all modules is, respectively, `"com.twitter"` and  `0.8.0` and each scala project is published for `2.10`, `2.11` and
do we care about the README on each of these branches reflecting the 0.7.x, etc and proper kryo version?

2017-01-04 00:09 UTC, sritchie-stripe commented on build.sbt
> -import ReleaseTransformations._
Are we also going to have to backport the doge release business? I think so.

2017-01-04 00:09 UTC, sritchie-stripe commented on chill-scala/src/main/scala/com/twitter/chill/KryoBase.scala
> +      getClassResolver.getRegistration(classOf[ClosureSerializer.Closure])
hmm, odd that this doesn't have coverage even though without it the tests failed.

2017-01-04 00:09 UTC, sritchie-stripe commented on project/plugins.sbt
>  addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.0")
we'll need to bump this as well - that'll get covered by the cherry-pick, I guess.

2017-01-04 00:09 UTC, sritchie-stripe commented
Huh, on 2.12:

```
[info] - should clean actual closures *** FAILED ***
[info]   java.lang.IllegalArgumentException:
[info]   at com.esotericsoftware.reflectasm.shaded.org.objectweb.asm.ClassReader.<init>(Unknown Source)
[info]   at com.esotericsoftware.reflectasm.shaded.org.objectweb.asm.ClassReader.<init>(Unknown Source)
[info]   at com.esotericsoftware.reflectasm.shaded.org.objectweb.asm.ClassReader.<init>(Unknown Source)
[info]   at com.twitter.chill.ClosureCleaner$.getClassReader(ClosureCleaner.scala:62)
[info]   at com.twitter.chill.ClosureCleaner$.getInnerClassesFn(ClosureCleaner.scala:112)
[info]   at com.twitter.chill.ClosureCleaner$.$anonfun$innerClassesOf$1(ClosureCleaner.scala:125)
[info]   at com.twitter.chill.ClosureCleaner$$$Lambda$1983/216374448.apply(Unknown Source)
[info]   at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
[info]   at com.twitter.chill.ClosureCleaner$.innerClassesOf(ClosureCleaner.scala:125)
[info]   at com.twitter.chill.ClosureCleaner$.getAccessedFields(ClosureCleaner.scala:133)
[info]   ...
```

2017-01-04 00:11 UTC, johnynek commented on project/plugins.sbt
>  addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.0")
huh, I guess we overlooked this.

2017-01-04 00:25 UTC, sritchie-stripe commented on chill-akka/src/main/scala/com/twitter/chill/akka/ActorRefSerializer.scala
> +    val path = ActorPath.fromString(input.readString())
Oh! Nice, I didn't realize that I DID merge these changes and that they're backwards compatible. Nice.

2017-01-04 00:26 UTC, sritchie-stripe commented
I think there's a race on the build, kick it again but 👍  on the code

2017-01-04 01:26 UTC, merged